openapi: 3.0.0
info:
  title: LCO Social App
  description: A learning app for backend in nodejs.
  version: 1.1.0

servers:
  - url: http://localhost:3000
    description: Local Host Server
  - url: https://lco-scocial.herokuapp.com/
    description: Production Server

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
